### ISSUE TITLE
Enroll existing tasks on US selection (edit mode)

### ISSUE THREAD

**Issue by norvegec** [ipatalas/vscode-sprint-planner#11]
Goal: edit existing tasks in user story for (current/any) sprint.
When: Right after autocompletion for User Story is made and it is enrolled into a `US#xxx - title` string
It would be nice to have: all existing Tasks enrolled as well right below, just like in new US mode.

**Comment by ipatalas** [comment]
Thanks for suggestion. That should be pretty easy to achieve. Putting it on the list :)

**Comment by bg-computercamp** [comment]
That is also a big request from here as well, if I can't stay out of devops dashboards, it would be so nice 👍

**Comment by ipatalas** [comment]
... in development :)
![image](https://user-images.githubusercontent.com/2623329/114453373-be6daf80-9bd9-11eb-9725-0ea52aea36a3.png)

**Comment by ipatalas** [comment]
Took a while, but it's there :)

https://github.com/ipatalas/vscode-sprint-planner#synchronize-tasks-from-azure-devops-since-050
