### ISSUE TITLE
Connecting to OnPremise Installation

### ISSUE THREAD

**Issue by gillissm** [ipatalas/vscode-sprint-planner#12]
I am trying to connect to an on premise install, but only receive a "Request failed with status code 404".

Does this not function with an on-premise setup?

**Comment by ipatalas** [comment]
Oh, I didn't even know such version exist.

Well.. currently it won't work because of that:
https://github.com/ipatalas/vscode-sprint-planner/blob/f70641c56c8f571129538a128c5e753b98d4ad92/src/utils/azure-client.ts#L74-L75

I can see a trial version of that so I might give it a try to find out how to get to the API. The docs are not very helpful in regards to on-premise version: https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1

If you find out what's the URL to on-premise API let me know - that will be very helpful.

**Comment by dennisl-UPR** [comment]
The on-premise solution is the old TFS that's been relabeled Azure DevOps Server.
It will accept NTLM authentication.

The Azure Repos plugin from MS is using NTLM authentication
https://github.com/Microsoft/azure-repos-vscode

**Comment by ipatalas** [comment]
If it's a totally different API then it's too much work. I hope it's only a matter of configuring the URL. Trying to install Azure DevOps Server locally but having some issues so far. When I succeed I'll have a look if it's possible.

**Comment by dennisl68-castra** [comment]
Make sure your using Azure DevOps Server 2019 Update 1 setup media.
The version before was a nightmare and I never did get SQL Server Reporting Server to play nice with the version before :/

**Comment by dennisl-UPR** [comment]
Make sure you're using Azure DevOps Server 2019 Update 1 setup media.
The version before was a nightmare and I never did get SQL Server Reporting Server to play nice :/

**Comment by gillissm** [comment]
I've only done a little exploring into the source for the plug-in, but pinpointed the only change needing to be adding an optional configuration value for the URL. (Confirmed this by hardcoding to my on-premise install, and successfully creating tasks.)

If the user does not set a URL then it defaults to its current usage.

I am not familiar enough with TypeScript or VS Code Extensions to make a proper PR but pinpointed the initial changes to be lines 49, 74, 75 in azure-client.ts ([azure-client.txt](https://github.com/ipatalas/vscode-sprint-planner/files/4047872/azure-client.txt)).

Which results in a minor addition to config.ts on line 18:
`    public devopurl: string | "https://dev.azure.com";`

Hope this helps.

**Comment by ipatalas** [comment]
That's great news! So the /{organization}/{project}, etc. parts stay the same, just the hostname is custom?

That was my best hope that it's gonna be like that. That means it's pretty easy to fix.

Since I don't have access to on premise installation can you help me testing it? 
When I make the change I'll get back here with the information on how to proceed?
I'd like to have it checked before publishing on the market.

**Comment by dennisl-UPR** [comment]
Sure, I can do some tests.

**Comment by ipatalas** [comment]
Just pushed some test code.

It's on a different branch: https://github.com/ipatalas/vscode-sprint-planner/tree/custom-url

If you could please have a look and let me know whether it works or not I'll be grateful.
The easiest way to run is to either clone the repo and switch branch or [download the branch](https://github.com/ipatalas/vscode-sprint-planner/archive/custom-url.zip).

Then just open in VSCode, hit F5 and it should all run flawlessly and override extension that's already installed in that instance of VSCode.

There is a new setting to change the URL. Please be careful and do not include the trailing slash. It's just to check if it works. I'll make it more bulletproof later before the release.

**Comment by dennisl-UPR** [comment]
I’ll have a look at it tomorrow (I’m currently away from my environment).

**Comment by ipatalas** [comment]
Hey, any news on that?

**Comment by dennisl-UPR** [comment]
Yeah, just toar down my environment and got it up and running again...

**Comment by dennisl-UPR** [comment]
It is stuck at Loading...

**Comment by dennisl-UPR** [comment]
OK, found Reset settings in VS Code Settings.

**Comment by dennisl-UPR** [comment]
Run into an error when trying to add a plan.

`Activating extension 'ipatalas.vscode-sprint-planner' failed: Cannot find module 'c:\Users\dsl\localrepos\vscode-sprint-planner-custom-url\out\extension.js'
Require stack:
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.`

**Comment by ipatalas** [comment]
How are you running the extension? From the code on that branch that I mentioned?
Did it work before? Maybe you can try from scratch? Clone/Download the branch to a new directory, open in VSCode and F5?

@gillissm any luck on your side?

**Comment by ipatalas** [comment]
Hey guys, any progress on checking that?

**Comment by ipatalas** [comment]
Ok guys.. can't do it myself. Closing for now. Let me know if you have time to test it.
