### ISSUE TITLE
Iterations Note being Detected

### ISSUE THREAD

**Issue by cgrisham** [ipatalas/vscode-sprint-planner#26]
When trying to define my iterations it isn't able to search my tenant for the proper iterations. 

Further when trying to push an update so that it uses current iterations I get a 401 error and the following returned in the output

```
[4:21:57 PM.881] Iteration not specified - will default to @CurrentIteration
[4:21:57 PM.881] Getting current iteration info...
[4:21:57 PM.943] ''
```

I have manually retrieved the Iteration ID and tried supplying that using 
`IT#47fa6b31-41b4-*****-985d-abdba9e604f0`

And still get the same message above.

**Comment by ipatalas** [comment]
Can you set `planner.azure-devops.debug` to `true` and try again? There should be much more verbose logging then, including request and response dump. Hope this will help figuring out what's the issue.
If that doesn't help can you make the following request using Postman or some other tool:
```
GET https://dev.azure.com/<organization>/<project>/_apis/work/teamsettings/iterations?$timeframe=current
Authorization: Basic PAT <your_token>
```
Let me know what are the results.

401 might mean expired/wrong token but that's only a guess for now.

**Comment by cgrisham** [comment]
Thanks for pointing me in correct direction I was able to resolve the issue. Had my Area and Team parameters in the config switched.
