### ISSUE TITLE
problems behind proxy

### ISSUE THREAD

**Issue by kiru-oss** [ipatalas/vscode-sprint-planner#28]
without proxy everything works fine.

But I have to work behind a proxy and there it doesn't work at all.

for sync:
Getting user story info...
Running the contributed command: 'sprintplanner.syncTasks' failed.

for publish:
Running the contributed command: '_vscode_delegate_cmd_knydxwib' failed.
Cannot read property 'toUpperCase' of undefined

sometimes I have this, when testing the extension I get
connect ETIMEDOUT 13.107.42.20:443

other extensions use the proxy setting that are set for windows:
$env:https_proxy
http://user:password@host:port

so my question is, can You add proxy support for the extension. Or tell me, what I have to do, to make it work

**Comment by ipatalas** [comment]
Oh.. that's interesting. This extension is using Axios under the hood which has proxy support. If you know a good public proxy I can test it. What I believe you are facing is a corporate proxy at work?
Maybe you can try cloning the repo and checking if it will work?
The change has to be done here:
https://github.com/ipatalas/vscode-sprint-planner/blob/3ad19abe44fe8ac29a9138d10fbb561b2ae0b572/src/utils/azure-client.ts#L55-L66

A following node has to be added to `axios.create`:
```JS
proxy: {
    protocol: 'https',
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'user',
      password: 'pass'
    }
  }
```

If that works then I can introduce settings for that. If it doesn't we'll find other way. Axios is not set in stone and I can change to a different lib.
Can you point to those other extensions which work for you? I can explore the code to see how they did it.
According to Axios docs it should automatically read $HTTPS_PROXY env var but maybe it doesn't work for some reason.

**Comment by kiru-oss** [comment]
first I found an issue that shows, we are not alone: [microsoft/vscode/12588](https://github.com/microsoft/vscode/issues/12588).

no I don't know a public proxy ;-(

I never build an extension myself, so I'll need some time before I'll answer again ;-(
So please hang on.

**Comment by ipatalas** [comment]
> no I don't know a public proxy ;-(

I'll try to find one.

> I never build an extension myself, so I'll need some time before I'll answer again ;-(
> So please hang on.

It's really easy. After you clone the repo and open it in VS Code you just hit F5 and it runs. Nothing more, really :)
That allows settings breakpoints and stuff. I can help in case you have any issues.

**Comment by kiru-oss** [comment]
You are right.

But I couldn't get it to work, neither with defining the proxy hardcoded, nor with http(s)Handler reading the http(s)_proxy from environment variable.

But maybe You might have a look at [vscode-restclient](https://github.com/Huachao/vscode-restclient). 
It works there!

**Comment by kiru-oss** [comment]
Sorry, me again.

when closing the browser, I found one more option I didn't test before ... and this one worked!

these two line before the axios.create:
```
const HttpsProxyAgent = require("https-proxy-agent");
var agents = new HttpsProxyAgent(process.env.https_proxy);
```

and these two in the axion.create {...
```
validateStatus: status => status === 200,
httpsAgent: agents,
proxy: false
```

And then my environment variables are used for the proxy!

**Comment by ipatalas** [comment]
Cool. Thanks for that. That's way easier now.
BTW `vscode-restclient` is using the same `https-proxy-agent` under the hood.

**Comment by kiru-oss** [comment]
so what comes next?
will You add some lines, or do I have create a pull request?

**Comment by ipatalas** [comment]
I will handle that, no worries.
Just to make sure it works fine I will first prepare a separate branch with that changes and ask you to test it in your environment first before releasing it to the public. Is that ok for you?

**Comment by kiru-oss** [comment]
sound great, thanks

**Comment by ipatalas** [comment]
Sorry, busy days, but here it is: https://github.com/ipatalas/vscode-sprint-planner/tree/proxy
Please have it checked whenever you have time. If it will be working fine then I'm gonna release it soon.

**Comment by kiru-oss** [comment]
No problem, I found time today and it worked! Great.

This one is ready from my side.
Thanks for the quick response.

**Comment by ipatalas** [comment]
Released new version. Proxy can also be overriden from configuration but in case it's empty it will read $HTTPS_PROXY or $HTTP_PROXY.

**Comment by kiru-oss** [comment]
work great, thanks a lot.
