### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by pcamdev** [ipatalas/vscode-sprint-planner#34]
Hi, I'm getting a "certificate has expired" error from your plug-in.  I've uninstalled and reinstalled, same error.

**Comment by ipatalas** [comment]
Can you show the exact message? I can only guess it's the Azure DevOps token that expired. They are not for ever. The default is 30 days, but you can change it to a year max.

**Comment by pcamdev** [comment]
Sure, this is the message:

***@***.***D76C35.D3262D40]

**Comment by ipatalas** [comment]
I meant the "Certificate has expired" message in VS Code.

**Comment by pcamdev** [comment]
That is the message in VS Code:
***@***.***D76C38.B268F3F0]

**Comment by ipatalas** [comment]
Can you post a screenshot?

**Comment by pcamdev** [comment]
I included a full screenshot in the last reply.  I will include as an attachment on this email, let me know if it doesn’t come through and I’ll zip it…
Thanks for taking the time to look into this.

**Comment by pcamdev** [comment]
ok, here's the screenshot:
![certError](https://user-images.githubusercontent.com/67656493/123700044-f6c27880-d82d-11eb-81a9-aee0b2aa172e.jpg)

**Comment by ipatalas** [comment]
Ok, that's better.

There are two things to check:
1. See Azure DevOps planner output channel for potentially more verbose message:
![image](https://user-images.githubusercontent.com/2623329/123700923-6f8ef800-d861-11eb-91a9-2b0c26353ec6.png)
2. Check Personal Access Token expiration date in Azure DevOps itself:
![image](https://user-images.githubusercontent.com/2623329/123701131-b977de00-d861-11eb-91c3-2c6f2a9280de.png)
![image](https://user-images.githubusercontent.com/2623329/123701165-c563a000-d861-11eb-832b-eba7b57bb5db.png)

**Comment by pcamdev** [comment]
I don't see a personal access token for Azure Planner in Azure DevOps...
here's the Azure DevOps Planner Output:
![image](https://user-images.githubusercontent.com/67656493/123702386-0ee7c700-d831-11eb-97ae-8809a03b0c7f.png)

**Comment by ipatalas** [comment]
![image](https://user-images.githubusercontent.com/2623329/123823765-c64a0f80-d8fd-11eb-8406-012736fca220.png)

**Comment by pcamdev** [comment]
This is what I have:
![image](https://user-images.githubusercontent.com/67656493/123824487-14deb600-d8cc-11eb-86e5-a32ead60770e.png)

**Comment by ipatalas** [comment]
Hmm.. ok, neither of these is expired so this must be something else. I wonder what it is.. 

Ok, please enable debug logging in extension's settings:
![image](https://user-images.githubusercontent.com/2623329/123824994-cd255200-d8fe-11eb-8173-61395cc73338.png)

After that turn on Dev Tools:
![image](https://user-images.githubusercontent.com/2623329/123825306-183f6500-d8ff-11eb-9cf8-b67fc92b6086.png)

..and then try again to reproduce the problem. 
We should hopefully see response error in Dev Tools console:
![image](https://user-images.githubusercontent.com/2623329/123825599-550b5c00-d8ff-11eb-8e7b-fcebb1782480.png)

Copy that error here or make a screenshot please.

**Comment by pcamdev** [comment]
![image](https://user-images.githubusercontent.com/67656493/123827176-64be7c80-d8ce-11eb-9b21-295170f20b6f.png)

**Comment by pcamdev** [comment]
I did a VS Code update last week, wondering if that may have been the cause...I'm going to try uninstalling/reinstalling VS Code...

**Comment by ipatalas** [comment]
Oh.. this looks like SSL certificate then. Something unrelated to this extension.
Any change you're using a HTTPS proxy to connect? If so then please check the certificate - it might have just expired.

**Comment by pcamdev** [comment]
Thanks for pointing me in the right direction, I was able to resolve it.

**Comment by ipatalas** [comment]
What was it?

**Comment by pcamdev** [comment]
It looks like it doesn't work when connected to VPN.  It worked once I disconnected from VPN.
