### ISSUE TITLE
Ability to add new Userstories

### ISSUE THREAD

**Issue by gitalexa** [ipatalas/vscode-sprint-planner#6]

**Comment by johndpalm** [comment]
Perhaps this could be accomplished similarly as the tasks are created now but starting with a Feature, then adding child User Stories.

`FE#123 My Feature
- This is a new User Story,
  - This is a task,
  - This a 2nd task
- This is another User Story,
  - This is another task below a user story
`

**Comment by ipatalas** [comment]
Resolved in 0.3.0.
I've used slightly different approach, see README for details.
