### ISSUE TITLE
Is azure devops server planner compatible?

### ISSUE THREAD

**Issue by sdjkx** [ipatalas/vscode-sprint-planner#7]
How do I configure it to be compatible with Azure DevOps Server 2019?

**Comment by ipatalas** [comment]
Is it not? Have you tried it? At the time it was being developed there was no 2019 version. 
However the API seems to be very similar.

I'm not sure I have access to this version to be able to check. How do I tell which version I'm using? Any idea?

**Comment by ipatalas** [comment]
Any update? Have you tried it? It seems like it should just work. I'm testing on the latest version in the cloud and everything works perfectly.
