### ISSUE TITLE
Token Permissions definition

### ISSUE THREAD

**Issue by kkum** [ipatalas/vscode-sprint-planner#8]
Hello
First of all thank you this extensions is exactly what i was looking for.
Can you please add to the Readme which settings should be enabled on the token so that we do not have to enable full access.
thank you

**Comment by ipatalas** [comment]
Oh. That's a very good point. I will do that later this week.
Thanks for the suggestion.

**Comment by ipatalas** [comment]
This is enough:
![image](https://user-images.githubusercontent.com/2623329/69572391-53abdc00-0fc4-11ea-8c65-740eb822f377.png)

It will be added to the README in next release.
